# Generated by Django 5.0.7 on 2024-11-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
