# Generated by Django 5.0.7 on 2024-11-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0003_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
