# Generated by Django 5.0.7 on 2024-11-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0004_alter_product_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
